### ISSUE TITLE
References fail

### ISSUE THREAD

**Issue by pohmelie** [pohmelie/cuda_tern#11]
yoba.js:

``` js
var yoba2 = require("./yoba2")

function yoba(a, b) {
    return a + b;
}

function foo(x) {
    return x;
}

yoba(foo(yoba(1, 2)), 3)
yoba2.b|ar()
```

yoba2.js:

``` js
function bar(a, b) {
    var c = [];
    return a * b;    
}

yoba(1, 2)
```

`|` — is cursor.
On references call:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/poh/tools/cudatext/py/cuda_tern/__init__.py", line 272, in show_usages
    normalize_caret(*caret),
  File "/home/poh/tools/cudatext/py/cuda_tern/__init__.py", line 365, in get_references
    expandWordForward=False,  # need when caret inside funcname
  File "/home/poh/tools/cudatext/py/cuda_tern/__init__.py", line 62, in do_request
    req = opener.open(url, s, timeout=TERN_TIMEOUT)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request
```

**Comment by Alexey-T** [comment]
Goto def -dont work too
"Require" not std JS operator; IMO need some lib to support it

**Comment by pohmelie** [comment]
Tern warn to be node.js and requirejs compliant... or I missed something.
http://ternjs.net/doc/manual.html#plugins

> The distribution currently comes plugins for parsing doc comments, and plugins for node.js and RequireJS, which teach the Tern server about the dependency management mechanisms defined by those systems (as well as, for node.js, including types for the built-in libraries).

**Comment by Alexey-T** [comment]
I dont know, then..

**Comment by pohmelie** [comment]
Probably tern guys can help. I will create issue tomorrow.

**Comment by Alexey-T** [comment]
Did u create issue at Tern

**Comment by Alexey-T** [comment]
What tern guys did reply?

**Comment by pohmelie** [comment]
Nothing special, it was my mistakes, but .tern-project file is required.
https://discuss.ternjs.net/t/require-and-go-to-definition/81/5

**Comment by Alexey-T** [comment]
Ok, i see exports was missed
will wait for tern-project file

**Comment by pohmelie** [comment]
Ok, it looks like it fixed now. This code is fine for complete and goto definition:
foo.js:
``` js
var bar = require("./bar")

function yoba(a, b) {
    return a + b;
}

function foo(x) {
    return x;
}

yoba(foo(yoba(1, 2)), 3)
bar.long_name_yoba()
```
bar.js:
``` js
function long_name_yoba(a, b) {
    var c = [];
    return a * b;
}

module.exports.long_|name_yoba = long_name_yoba
```
.tern-project:
``` json
{
    "libs": [],
    "loadEagerly": [
        "**/*.js"
    ],
    "plugins": {
        "node": {}
    }
}
```
