### ISSUE TITLE
Show err, if no Tern installed

### ISSUE THREAD

**Issue by Alexey-T** [pohmelie/cuda_tern#4]
when  no Tern,

```
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/home/user/.cudatext/py/cuda_tern/__init__.py", line 14, in <module>
    stdout=subprocess.PIPE,
  File "/usr/lib/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.4/subprocess.py", line 1457, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'tern'
```

**Comment by Alexey-T** [comment]
fixd.
