### ISSUE TITLE
Show er, if Tern cant start

### ISSUE THREAD

**Issue by Alexey-T** [pohmelie/cuda_tern#6]
i cannot run tern on 2nd PC. "tern" dont give output.
Cud shows

```
Traceback (most recent call last):
  File "/usr/lib/python3.4/http/client.py", line 786, in _get_hostport
    port = int(host[i+1:])
ValueError: invalid literal for int() with base 10: 'None'
```

**Comment by pohmelie** [comment]
Is this a full traceback? Which line of cuda_tern code is called?

**Comment by Alexey-T** [comment]
Full. i think process running

**Comment by pohmelie** [comment]
It is definitely not full traceback, since there is no `__init__.py` code from `cuda_tern`. Recheck it please.

**Comment by Alexey-T** [comment]
I renamed "node" to "node_"
To repeat it
Now is
~~~
Python 3.4.3
Setting icons: AwOken_24x24
Traceback (most recent call last):
  File "/usr/lib/python3.4/http/client.py", line 786, in _get_hostport
    port = int(host[i+1:])
ValueError: invalid literal for int() with base 10: 'None'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/.cudatext/py/cuda_tern/__init__.py", line 53, in wrapped
    return f(self, ed_self)
  File "/home/user/.cudatext/py/cuda_tern/__init__.py", line 66, in wrapped
    return f(self, ed_self, filename, text, normalize_caret(*caret))
  File "/home/user/.cudatext/py/cuda_tern/__init__.py", line 77, in on_complete
    result = self.complete(filename, text, caret)
  File "/home/user/.cudatext/py/cuda_tern/__init__.py", line 173, in complete
    docs=True,
  File "/home/user/.cudatext/py/cuda_tern/__init__.py", line 229, in request
    req = opener.open(url, s, 1)
  File "/usr/lib/python3.4/urllib/request.py", line 463, in open
    response = self._open(req, data)
  File "/usr/lib/python3.4/urllib/request.py", line 481, in _open
    '_open', req)
  File "/usr/lib/python3.4/urllib/request.py", line 441, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 1210, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.4/urllib/request.py", line 1152, in do_open
    h = http_class(host, timeout=req.timeout, **http_conn_args)
  File "/usr/lib/python3.4/http/client.py", line 750, in __init__
    (self.host, self.port) = self._get_hostport(host, port)
  File "/usr/lib/python3.4/http/client.py", line 791, in _get_hostport
    raise InvalidURL("nonnumeric port: '%s'" % host[i+1:])
http.client.InvalidURL: nonnumeric port: 'None'
~~~

**Comment by Alexey-T** [comment]
fixed
